name: Fix Gemini IA

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: Corriger Gemini IA
        run: run: python3 fix_gemini3.py

      - name: Push
        run: |
          git config user.name "Saloni Bot"
          git config user.email "bot@saloni.app"
          git add index.html
          git commit -m "Fix Gemini IA placement" || echo "Rien"
          git push
